FROM python:3
LABEL maintainer="rmontesg@resuelve.mx"

ENV PYTHONUNBUFFERED 1

RUN pip3 install --no-cache-dir pip -U \
	numpy==1.14.2 \
	pandas==0.22.0 \
	python-dateutil==2.7.2 \
	pytz==2018.3 \
	six==1.11.0 \
	scipy==1.0.0 \
	wheel==0.31.0
